<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.dao.support.DataAccessUtilsTests" tests="10" skipped="0" failures="0" errors="0" timestamp="2020-06-22T06:04:35" hostname="aiguoxindeMacBook-Pro.local" time="0.089">
  <properties/>
  <testcase name="withString()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.013"/>
  <testcase name="withInteger()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.004"/>
  <testcase name="exceptionTranslationWithNoTranslation()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="withDate()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.033"/>
  <testcase name="withLong()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="withTooLargeCollection()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.019"/>
  <testcase name="withSameIntegerInstanceTwice()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.0"/>
  <testcase name="withEmptyCollection()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.006"/>
  <testcase name="withEquivalentIntegerInstanceTwice()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.002"/>
  <testcase name="exceptionTranslationWithTranslation()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.003"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
